<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asc</string>
		<string>asm</string>
		<string>inc</string>
		<string>as</string>
	</array>
	<key>name</key>
	<string>MSX Z80 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(0x[0-9a-fA-F]+)\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0b[01]+)\b</string>
			<key>name</key>
			<string>constant.numeric.binary</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>

		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s|^)\.(?=(?i)abort|align|balign|balignl|balignw|comm|equ|equiv|err|extern|fail|file|global|globl|hidden|incbin|incdir|include|internal|lcomm|local|org|p2align|p2alignl|p2alignw|protected|set|size|skip|space|stabs|stabn|stabd|swbeg|type|weak|zero|else|elseif|endif|endm|endr|if|ifeq|ifne|ifgt|ifge|iflt|ifle|ifb|ifnb|ifc|ifnc|ifdef|ifndef|irp|irpc|macro|list|nolist|rept)\b</string>
			<key>name</key>
			<string>punctuation.whitespace.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:abort|align|balign|balignl|balignw|comm|equ|equiv|err|extern|fail|file|global|globl|hidden|incbin|incdir|include|internal|lcomm|local|org|p2align|p2alignl|p2alignw|protected|set|size|skip|space|stabs|stabn|stabd|swbeg|type|weak|zero|else|elseif|endif|endm|endr|if|ifeq|ifne|ifgt|ifge|iflt|ifle|ifb|ifnb|ifc|ifnc|ifdef|ifndef|irp|irpc|macro|list|nolist|rept)\b</string>
			<key>name</key>
			<string>support.type.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\(\d+|[a-zA-Z_][a-zA-Z0-9_]*)\b</string>
			<key>name</key>
			<string>variable.other.constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s|^)\.(?=(?i)2byte|4byte|8byte|ascii|ds|deb|defw|defs|byte|double|float|half|int|long|quad|short|single|string|uahalf|ualong|uaquad|uashort|uaword|word)\b</string>
			<key>name</key>
			<string>punctuation.whitespace.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:2byte|4byte|8byte|ascii|ds|deb|defw|defs|byte|double|float|half|int|long|quad|short|single|string|uahalf|ualong|uaquad|uashort|uaword|word)\b</string>
			<key>name</key>
			<string>storage.type.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s|^)\.(?=(?i)bss|data|dpage|rodata|sbss|sdata|sdata2|stab|stabstr|text|tocd|section|pushsection|popsection)\b</string>
			<key>name</key>
			<string>entity.name.variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:bss|data|dpage|rodata|sbss|sdata|sdata2|stab|stabstr|text|tocd|section|pushsection|popsection)\b</string>
			<key>name</key>
			<string>entity.name.variable</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.asm.z80</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.asm.z80</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.include.asm.z80</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.character.begin.asm.z80</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.character.end.asm.z80</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.include.asm.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(ADC|ADD|AND|BIT|CCF|CP|CPD|CPDR|CPI|CPIR|CPL|DAA|DEC|DI|EI|EX|EXX|HALT|IM|IN|INC|IND|INDR|INI|INIR|LD|LDD|LDDR|LDI|LDIR|NEG|NOP|NV|OR|OTDR|OTIR|OUT|OUTD|OUTI|POP|PUSH|RES|RL|RLA|RLC|RLCA|RLD|RR|RRA|RRC|RRCA|RRD|RST|SBC|SCF|SET|SLA|SRA|SRL|SUB|XOR))\b</string>
			<key>name</key>
			<string>keyword.mnemonic.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(jr|jp|call|ret)\s+(c|nc|z|nz|p|m|pe|po)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.asm</string> 
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.control.asm</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(jr|jp|call|ret|djnz))\b</string>
			<key>name</key>
			<string>keyword.control.asm</string> 
		</dict>
		<dict>
			<key>match</key>
			<string>^\d{5}</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(A|B|C|D|E|F|H|L|I|R|IX|IY|AF|BC|DE|HL|PC|SP|AF'))\b</string>
			<key>name</key>
			<string>storage.type.asm.z80</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.z80</string>
	<key>uuid</key>
	<string>84DDB367-0875-4FF3-8047-D3FF2988B3C9</string>
</dict>
</plist>
